--- # Error handling example#2
- hosts: "{{ target_hosts }}"
  become: yes
  vars:
    target_service: apache
  tasks:
    - name: Install Software
      block:
        - service:
            name: "{{ target_service }}"
            state: started
          register: service_status
      rescue:
        - debug: 
            var: service_status
      always:
        - debug:
            msg: "Tried to ensure service was running"
