--- # Ansible Facts Example
- hosts: remote
  tasks:
    - name: create a file
      lineinfile:
        path: /home/cloud_user/hostname
        create: yes
        line: "{{ ansible_hostname }}"
    - name: access magic variable
      lineinfile:
        path: /home/ansible/hostname
        line: "{{ hostvars['localhost']['ansible_default_ipv4']['address'] }}"
        # Other magic variables are groups, group name and inventory hostname 

