---
- name: Install Docker on Kali Linux
  hosts: "{{ target_hosts }}"
  become: true
  vars:
    docker_users: []  # Add users here (e.g., ["kali"])

  tasks:
    - name: Remove old Docker packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-engine
          - containerd
          - runc
        state: absent
      ignore_errors: yes

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present

    - name: Create directory for GPG keys
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: 0755

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: 0644

    - name: Determine Debian codename (Kali base)
      ansible.builtin.shell: |
        . /etc/os-release
        if [ "$ID" = "kali" ]; then
          echo "bookworm"  # Kali 2023+ uses Debian bookworm
        else
          echo "$VERSION_CODENAME"
        fi
      register: debian_codename
      changed_when: false

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ debian_codename.stdout }} stable"
        state: present
        filename: docker.list
        update_cache: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      ansible.builtin.debug:
        msg: "Docker installed: {{ docker_version.stdout }}"

    - name: Add users to Docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{ docker_users }}"
      when: docker_users | length > 0
