---
- name: Install Docker on Ubuntu and Red Hat systems
  hosts: ALL
  become: true
  vars:
    docker_users: []  # Add users who should have Docker permissions (e.g., ["ubuntu", "ansible"])

  tasks:
    - name: Check OS family
      ansible.builtin.set_fact:
        os_family: "{{ ansible_facts['os_family'] }}"

    - name: Install dependencies (Red Hat)
      ansible.builtin.package:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: os_family == "RedHat"

    - name: Install dependencies (Ubuntu)
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: os_family == "Debian"

    - name: Add Docker GPG key (Ubuntu)
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: os_family == "Debian"

    - name: Add Docker repository (Ubuntu)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        state: present
        update_cache: yes
      when: os_family == "Debian"

    - name: Add Docker repository (Red Hat)
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes
      when: os_family == "RedHat"

    - name: Install Docker CE
      ansible.builtin.package:
        name: docker-ce
        state: present
      when: os_family == "Debian" or os_family == "RedHat"

    - name: Install Docker CE (Red Hat)
      ansible.builtin.package:
        name: docker-ce
        state: present
      when: os_family == "RedHat"

    - name: Ensure Docker is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add users to Docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{ docker_users }}"
      when: docker_users | length > 0
