---
- name: Install Docker on Ubuntu and Red Hat systems
  hosts: "{{ target_hosts }}"
  become: yes
  tasks:

    - name: Install dependencies on Ubuntu
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key (Ubuntu)
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      when: ansible_os_family == "Debian"

    - name: Add Docker repository (Ubuntu)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker on Ubuntu
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install dependencies on Red Hat
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add Docker repository (Red Hat)
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_os_family == "RedHat"

    - name: Install Docker on Red Hat
      yum:
        name: docker-ce
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

