--- #tags example
- hosts: "{{ target_hosts }}"
  tasks:
    - name: install elinks
      become: yes
      apt:
        name: elinks
        state: latest
      tags:
        - software

    - name: Add line to text file
      lineinfile:
        path: /home/cloud_user/ark/github/Ansible/tag-test.txt
        create: yes
        line: "Tag called"
      tags: 
        - files
        - config
    - name: copy tag file
      copy: 
        src: /home/cloud_user/ark/github/Ansible/tag-test.txt 
        dest: /home/cloud_user/ark/copied.txt
      tags:
        - config     


